services:
  db:
    image: mariadb:10.11
    # 環境変数はドキュメントで調べる
    # https://hub.docker.com/_/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    volumes:
      # コンテナ内の/var/lib/mysqlディレクトリにdb-dataという名前付きボリュームをマウント
      - db-data:/var/lib/mysql
volumes:
  db-data: